### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by mintisan** [Arshdeep-Singh-01/Human-Activity-Recognition-using-MutliHead-Convolutional-Attention#2]
Weather Ubuntu or Windows, torch 2.1 or 2.0, encountered runtime error as below after data processed:

```
➜  CNN_HAR git:(main) ✗ python3 train.py                      
Using torch 2.1.1+cu118
Device cuda
Error at line number:  281873
Error at line number:  281874
Error at line number:  281875
^T^T


torch.Size([274658, 1, 90, 3])
  0%|                                                                                                      | 0/20 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/mintisan/Workplaces/CNN_HAR/train.py", line 73, in <module>
    trainModel(model, train_data_loader, loss, optimizer, 20)
  File "/home/mintisan/Workplaces/CNN_HAR/train.py", line 48, in trainModel
    preds = model(sequence)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mintisan/Workplaces/CNN_HAR/layers/Attention/MutliHeadAttention.py", line 41, in forward
    q, k, v = self.qkv(x)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mintisan/Workplaces/CNN_HAR/layers/Attention/QKVmatrix.py", line 27, in forward
    q = self.QMatrix(x)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mintisan/Workplaces/CNN_HAR/layers/Attention/QKVmatrix.py", line 11, in forward
    x = self.fcl(x)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mintisan/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
➜  CNN_HAR git:(main) ✗ 

```

**Comment by mintisan** [comment]
Got the reason:

![image](https://github.com/Arshdeep-Singh-01/Human-Activity-Recognition-using-MutliHead-Convolutional-Attention/assets/9136049/706e4092-c163-48bc-802c-774a3ee2db76)

**Comment by Arshdeep-Singh-01** [comment]
All good?
I have done most of the work in colab, so if you need that one, I can share the notebook!

**Comment by izonewonyoung** [comment]
Hi,I have the same problem.Can you tell me how to fix it?I don't find the code you give.
